services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: makasouk
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: makasouk
      MYSQL_PASSWORD: makasouk
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mysql_data:
